# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk12

services:
  - postgresql

before_install:
  - psql -c 'create database accident;' -U postgres
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - johnom2012@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always
env:
  global:
    - CODECOV_TOKEN="02e6dcca-a9f9-40aa-8fea-de7fd69696f2"